sudo: false
language: node_js
node_js:
  - 15
cache: npm
branches:
  only:
    - master # build master branch only
install:
  - yarn
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_token
  keep-history: true
  on:
    branch: master
  local-dir: public
